from custom_components.ld2410.const import (
    CONNECTABLE_SUPPORTED_MODEL_TYPES,
    NON_CONNECTABLE_SUPPORTED_MODEL_TYPES,
    SUPPORTED_MODEL_TYPES,
)
from custom_components.ld2410.api.ld2410 import LD2410Model


def test_ld2410_is_connectable():
    assert LD2410Model.LD2410 in CONNECTABLE_SUPPORTED_MODEL_TYPES
    assert LD2410Model.LD2410 not in NON_CONNECTABLE_SUPPORTED_MODEL_TYPES
    assert LD2410Model.LD2410 in SUPPORTED_MODEL_TYPES
